### ISSUE TITLE
Having problems using MOQ

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [jozefizso/SystemWrapper#55] opened 2018-12-03 21:11 UTC
here's my code:
```csharp
           var diMock = new Mock<IDirectoryInfo>();  
            diMock.Setup(i => i.Create());  
            try  
            {  
                var obj = diMock.Object;  
            }catch(Exception ex)  
            {  
                //SYSTEM.Runtime.Remoting.ObjRef exception here...  
            }
```

any ideas?

**Comment by SlowLogicBoy** [comment] 2018-12-04 07:49
I can't reproduce this.
Moq: 4.10.0
SystemWrapper: 0.25.0.186

**Comment by jozefizso** [comment] 2019-11-03 18:07
Closing as external issue.

**Closed by jozefizso** 2019-11-03 18:07 UTC
Labels: external
